version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=poc_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
    networks:
      - test-net
      
  spring-boot-jpa-app:
    image: spring-cust-annotations-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    networks:
      - test-net
      
networks:
  test-net:
    driver: bridge      